name: universal_player_app
description: Cross-platform voice-controlled video app using universal_player.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  universal_player:
    path: ../universal_player
  supabase_flutter: ^2.5.6
  flutter_stripe: ^11.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
