name: universal_player
description: Unified cross-platform media player controller with pluggable backends, source parsers, voice control, and UI controls.
version: 0.1.0
homepage: https://example.com/universal_player

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  collection: ^1.18.0
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  logging: ^1.2.0
  csv: ^6.0.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.universal.player
        pluginClass: UniversalPlayerPlugin
      ios:
        pluginClass: UniversalPlayerPlugin
